apiVersion: v1
kind: Pod
metadata:
  name: webserver-pod
  namespace: project1
spec:
  containers:
  - name: webserver-container
    image: nginx:latest
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: web-content
    - mountPath: /data
      name: data-volume
  tolerations:
  - key: "node"
    operator: "Equal"
    value: "webserver"
    effect: "NoSchedule"
  volumes:
  - name: web-content
    hostPath:
      path: /opt/webserver
      type: Directory
  - name: data-volume
    persistentVolumeClaim:
      claimName: data-pvc

